// AUTO-GENERATED by scratch/discover_all_pools.js
// Pharos Atlantic Testnet (chainId: 688689) — 2026-05-17T13:20:52.048Z
// DO NOT EDIT MANUALLY — re-run the discovery script to update

export interface TokenMeta {
    address: string;
    symbol: string;
    name: string;
    decimals: number;
    chainId: number;
}

export const PHAROS_TOKENS: TokenMeta[] = [
    { address: '0x568188ecd98429f5f4c14b4cfd548cd51d443a09', symbol: 'AQ-stNova', name: 'AquaFlux stNova', decimals: 18, chainId: 688689 },
    { address: '0xc3206025fcc8bd0414ae315936e8c4df64afa570', symbol: 'AQ-TPC', name: 'AquaFlux TPC', decimals: 18, chainId: 688689 },
    { address: '0xd97d27e267d8ee5ed346366828791378f9e0145b', symbol: 'AQ-UST', name: 'AquaFlux UST', decimals: 18, chainId: 688689 },
    { address: '0xa020cd049acd8725100b7bb800557f7cc1adfb66', symbol: 'C-TPC', name: 'C TPC 31DEC2026', decimals: 18, chainId: 688689 },
    { address: '0xc3643070a6e7aace696710e3a685108d93c09ad6', symbol: 'C-UST', name: 'C UST 30JUN2026', decimals: 18, chainId: 688689 },
    { address: '0x285a7a9a14070ec8c3b193b8dc07cf58dc33e8bd', symbol: 'mmmmm', name: 'mmmmm', decimals: 18, chainId: 688689 },
    { address: '0xe2e9f3b60115bcb516ec0395e864e4785def751f', symbol: 'P-stNova', name: 'P stNova 31DEC2026', decimals: 18, chainId: 688689 },
    { address: '0xbf43ff0baff5f9a38a5c278b92b8a65750122129', symbol: 'P-TPC', name: 'P TPC 31DEC2026', decimals: 18, chainId: 688689 },
    { address: '0x2bb80cfd6f2b14f6b93b1269c9a19f2dc0933344', symbol: 'P-UST', name: 'P UST 30JUN2026', decimals: 18, chainId: 688689 },
    { address: '0xcf2bdbae0271dd07cceee55d09808d35c6c51014', symbol: 'S-stNova', name: 'S stNova 31DEC2026', decimals: 18, chainId: 688689 },
    { address: '0x6bb00ad0c718d1227b8f96a422e47aa7c5efca47', symbol: 'S-TPC', name: 'S TPC 31DEC2026', decimals: 18, chainId: 688689 },
    { address: '0x93bc7267d802201e51926bef331de80c965ec55f', symbol: 'S-UST', name: 'S UST 30JUN2026', decimals: 18, chainId: 688689 },
    { address: '0x4436c5e183e6b3ad64a83f6d0a82a030d81c08cf', symbol: 'SAFI', name: 'SAFI', decimals: 18, chainId: 688689 },
    { address: '0x9306bb32b6211bc409466354178fb61f25d75eb0', symbol: 'SS-STNOVA-31DEC2026', name: 'Staked Nova Surplus', decimals: 18, chainId: 688689 },
    { address: '0xdf13c9d473cfbcea9cacae75f877927b7302d8e7', symbol: 'SS-TPC-31DEC2026', name: 'Test Private Credit Surplus', decimals: 18, chainId: 688689 },
    { address: '0x4de6a1d9b8a541221031296506c19536efdf177a', symbol: 'SS-UST-30JUN2026', name: 'US Treasury Bond Surplus', decimals: 18, chainId: 688689 },
    { address: '0xe0be08c77f415f577a1b3a9ad7a1df1479564ec8', symbol: 'USDC', name: 'USD Coin', decimals: 6, chainId: 688689 },
    { address: '0xb691f00682feef63bc73f41c380ff648d73c6a2c', symbol: 'USDC', name: 'TEST USDC', decimals: 6, chainId: 688689 },
    { address: '0xe7e84b8b4f39c507499c40b4ac199b050e2882d5', symbol: 'USDT', name: 'Tether USD', decimals: 6, chainId: 688689 },
    { address: '0x0c64f03eea5c30946d5c55b4b532d08ad74638a4', symbol: 'WBTC', name: 'Wrapped BTC', decimals: 18, chainId: 688689 },
    { address: '0x7d211f77525ea39a0592794f793cc1036eeaccd5', symbol: 'WETH', name: 'Wrapped ETH', decimals: 18, chainId: 688689 },
    { address: '0x838800b758277cc111b2d48ab01e5e164f8e9471', symbol: 'WPHRS', name: 'Wrapped Pharos', decimals: 18, chainId: 688689 },
];

export const PHAROS_TOKEN_MAP = new Map<string, TokenMeta>(
    PHAROS_TOKENS.map(t => [t.address, t])
);
