/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FaroLinkRouter {
  export type HopDataStruct = {
    bridgeAdapter: AddressLike;
    callData: BytesLike;
    tokenIn: AddressLike;
    amountIn: BigNumberish;
    isNative: boolean;
  };

  export type HopDataStructOutput = [
    bridgeAdapter: string,
    callData: string,
    tokenIn: string,
    amountIn: bigint,
    isNative: boolean
  ] & {
    bridgeAdapter: string;
    callData: string;
    tokenIn: string;
    amountIn: bigint;
    isNative: boolean;
  };
}

export interface FaroLinkRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveAdapter"
      | "approvedAdapters"
      | "executePath"
      | "feeBps"
      | "feeCollector"
      | "owner"
      | "paused"
      | "renounceOwnership"
      | "rescueETH"
      | "rescueToken"
      | "setFeeBps"
      | "setFeeCollector"
      | "setPaused"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdapterApproved"
      | "FeeBpsUpdated"
      | "FeeCollectorUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "ProtocolFeeCollected"
      | "RouteExecuted"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveAdapter",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedAdapters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executePath",
    values: [FaroLinkRouter.HopDataStruct[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueETH",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedAdapters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rescueETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rescueToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AdapterApprovedEvent {
  export type InputTuple = [adapter: AddressLike, approved: boolean];
  export type OutputTuple = [adapter: string, approved: boolean];
  export interface OutputObject {
    adapter: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeBpsUpdatedEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectorUpdatedEvent {
  export type InputTuple = [newFeeCollector: AddressLike];
  export type OutputTuple = [newFeeCollector: string];
  export interface OutputObject {
    newFeeCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeeCollectedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    routeId: BytesLike,
    tokenIn: AddressLike,
    amountIn: BigNumberish,
    hopCount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    routeId: string,
    tokenIn: string,
    amountIn: bigint,
    hopCount: bigint
  ];
  export interface OutputObject {
    user: string;
    routeId: string;
    tokenIn: string;
    amountIn: bigint;
    hopCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FaroLinkRouter extends BaseContract {
  connect(runner?: ContractRunner | null): FaroLinkRouter;
  waitForDeployment(): Promise<this>;

  interface: FaroLinkRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveAdapter: TypedContractMethod<
    [adapter: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  approvedAdapters: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  executePath: TypedContractMethod<
    [hops: FaroLinkRouter.HopDataStruct[], routeId: BytesLike],
    [void],
    "payable"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  feeCollector: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rescueETH: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rescueToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeBps: TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;

  setFeeCollector: TypedContractMethod<
    [_fc: AddressLike],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveAdapter"
  ): TypedContractMethod<
    [adapter: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvedAdapters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "executePath"
  ): TypedContractMethod<
    [hops: FaroLinkRouter.HopDataStruct[], routeId: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueETH"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescueToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeBps"
  ): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[_fc: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdapterApproved"
  ): TypedContractEvent<
    AdapterApprovedEvent.InputTuple,
    AdapterApprovedEvent.OutputTuple,
    AdapterApprovedEvent.OutputObject
  >;
  getEvent(
    key: "FeeBpsUpdated"
  ): TypedContractEvent<
    FeeBpsUpdatedEvent.InputTuple,
    FeeBpsUpdatedEvent.OutputTuple,
    FeeBpsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollectorUpdated"
  ): TypedContractEvent<
    FeeCollectorUpdatedEvent.InputTuple,
    FeeCollectorUpdatedEvent.OutputTuple,
    FeeCollectorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeeCollected"
  ): TypedContractEvent<
    ProtocolFeeCollectedEvent.InputTuple,
    ProtocolFeeCollectedEvent.OutputTuple,
    ProtocolFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "RouteExecuted"
  ): TypedContractEvent<
    RouteExecutedEvent.InputTuple,
    RouteExecutedEvent.OutputTuple,
    RouteExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AdapterApproved(address,bool)": TypedContractEvent<
      AdapterApprovedEvent.InputTuple,
      AdapterApprovedEvent.OutputTuple,
      AdapterApprovedEvent.OutputObject
    >;
    AdapterApproved: TypedContractEvent<
      AdapterApprovedEvent.InputTuple,
      AdapterApprovedEvent.OutputTuple,
      AdapterApprovedEvent.OutputObject
    >;

    "FeeBpsUpdated(uint256)": TypedContractEvent<
      FeeBpsUpdatedEvent.InputTuple,
      FeeBpsUpdatedEvent.OutputTuple,
      FeeBpsUpdatedEvent.OutputObject
    >;
    FeeBpsUpdated: TypedContractEvent<
      FeeBpsUpdatedEvent.InputTuple,
      FeeBpsUpdatedEvent.OutputTuple,
      FeeBpsUpdatedEvent.OutputObject
    >;

    "FeeCollectorUpdated(address)": TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;
    FeeCollectorUpdated: TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProtocolFeeCollected(address,uint256)": TypedContractEvent<
      ProtocolFeeCollectedEvent.InputTuple,
      ProtocolFeeCollectedEvent.OutputTuple,
      ProtocolFeeCollectedEvent.OutputObject
    >;
    ProtocolFeeCollected: TypedContractEvent<
      ProtocolFeeCollectedEvent.InputTuple,
      ProtocolFeeCollectedEvent.OutputTuple,
      ProtocolFeeCollectedEvent.OutputObject
    >;

    "RouteExecuted(address,bytes32,address,uint256,uint256)": TypedContractEvent<
      RouteExecutedEvent.InputTuple,
      RouteExecutedEvent.OutputTuple,
      RouteExecutedEvent.OutputObject
    >;
    RouteExecuted: TypedContractEvent<
      RouteExecutedEvent.InputTuple,
      RouteExecutedEvent.OutputTuple,
      RouteExecutedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
